# Generated by Django 6.0.3 on 2026-03-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item sold'), ('RESTOCKING', 'Item restocking in few days')], default='Sold', max_length=100),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item sold'), ('RESTOCKING', 'Item restocking in few days')], default='Sold', max_length=100),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Item ready to be purchased'), ('SOLD', 'Item sold'), ('RESTOCKING', 'Item restocking in few days')], default='Sold', max_length=100),
        ),
    ]
